spring:
  application:
    name: learning-carnival
#  ai:
#    openai:
#      api-key: ${api-key}
#      chat:
#        options:
#          model : gpt-3.5-turbo
#openai:
#  api:
#    url: https://api.groq.com/openai/v1
#    key : ${groq-api-key}
#groq:
#  api:
#    key : ${groq-api-key}
#    url: https://api.groq.com/openai/v1/chat/completions